/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVehiculosRouteImport } from './routes/_app.vehiculos'
import { Route as AppOrdenesCompraRouteImport } from './routes/_app.ordenes-compra'
import { Route as AppOperadoresRouteImport } from './routes/_app.operadores'
import { Route as AppGruasRouteImport } from './routes/_app.gruas'
import { Route as AppCotizacionesRouteImport } from './routes/_app.cotizaciones'
import { Route as AppCostosRouteImport } from './routes/_app.costos'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'
import { Route as AppCierresRouteImport } from './routes/_app.cierres'
import { Route as AppBodegaRouteImport } from './routes/_app.bodega'
import { Route as AppOrdenesIndexRouteImport } from './routes/_app.ordenes.index'
import { Route as AppClientesIndexRouteImport } from './routes/_app.clientes.index'
import { Route as AppClientesClienteIdRouteImport } from './routes/_app.clientes.$clienteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiculosRoute = AppVehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdenesCompraRoute = AppOrdenesCompraRouteImport.update({
  id: '/ordenes-compra',
  path: '/ordenes-compra',
  getParentRoute: () => AppRoute,
} as any)
const AppOperadoresRoute = AppOperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => AppRoute,
} as any)
const AppGruasRoute = AppGruasRouteImport.update({
  id: '/gruas',
  path: '/gruas',
  getParentRoute: () => AppRoute,
} as any)
const AppCotizacionesRoute = AppCotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppCostosRoute = AppCostosRouteImport.update({
  id: '/costos',
  path: '/costos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCierresRoute = AppCierresRouteImport.update({
  id: '/cierres',
  path: '/cierres',
  getParentRoute: () => AppRoute,
} as any)
const AppBodegaRoute = AppBodegaRouteImport.update({
  id: '/bodega',
  path: '/bodega',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdenesIndexRoute = AppOrdenesIndexRouteImport.update({
  id: '/ordenes/',
  path: '/ordenes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bodega': typeof AppBodegaRoute
  '/cierres': typeof AppCierresRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/costos': typeof AppCostosRoute
  '/cotizaciones': typeof AppCotizacionesRoute
  '/gruas': typeof AppGruasRoute
  '/operadores': typeof AppOperadoresRoute
  '/ordenes-compra': typeof AppOrdenesCompraRoute
  '/vehiculos': typeof AppVehiculosRoute
  '/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/ordenes/': typeof AppOrdenesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bodega': typeof AppBodegaRoute
  '/cierres': typeof AppCierresRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/costos': typeof AppCostosRoute
  '/cotizaciones': typeof AppCotizacionesRoute
  '/gruas': typeof AppGruasRoute
  '/operadores': typeof AppOperadoresRoute
  '/ordenes-compra': typeof AppOrdenesCompraRoute
  '/vehiculos': typeof AppVehiculosRoute
  '/': typeof AppIndexRoute
  '/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/clientes': typeof AppClientesIndexRoute
  '/ordenes': typeof AppOrdenesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bodega': typeof AppBodegaRoute
  '/_app/cierres': typeof AppCierresRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/costos': typeof AppCostosRoute
  '/_app/cotizaciones': typeof AppCotizacionesRoute
  '/_app/gruas': typeof AppGruasRoute
  '/_app/operadores': typeof AppOperadoresRoute
  '/_app/ordenes-compra': typeof AppOrdenesCompraRoute
  '/_app/vehiculos': typeof AppVehiculosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/ordenes/': typeof AppOrdenesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bodega'
    | '/cierres'
    | '/configuracion'
    | '/costos'
    | '/cotizaciones'
    | '/gruas'
    | '/operadores'
    | '/ordenes-compra'
    | '/vehiculos'
    | '/clientes/$clienteId'
    | '/clientes/'
    | '/ordenes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bodega'
    | '/cierres'
    | '/configuracion'
    | '/costos'
    | '/cotizaciones'
    | '/gruas'
    | '/operadores'
    | '/ordenes-compra'
    | '/vehiculos'
    | '/'
    | '/clientes/$clienteId'
    | '/clientes'
    | '/ordenes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bodega'
    | '/_app/cierres'
    | '/_app/configuracion'
    | '/_app/costos'
    | '/_app/cotizaciones'
    | '/_app/gruas'
    | '/_app/operadores'
    | '/_app/ordenes-compra'
    | '/_app/vehiculos'
    | '/_app/'
    | '/_app/clientes/$clienteId'
    | '/_app/clientes/'
    | '/_app/ordenes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehiculos': {
      id: '/_app/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof AppVehiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordenes-compra': {
      id: '/_app/ordenes-compra'
      path: '/ordenes-compra'
      fullPath: '/ordenes-compra'
      preLoaderRoute: typeof AppOrdenesCompraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operadores': {
      id: '/_app/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof AppOperadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gruas': {
      id: '/_app/gruas'
      path: '/gruas'
      fullPath: '/gruas'
      preLoaderRoute: typeof AppGruasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cotizaciones': {
      id: '/_app/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof AppCotizacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costos': {
      id: '/_app/costos'
      path: '/costos'
      fullPath: '/costos'
      preLoaderRoute: typeof AppCostosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cierres': {
      id: '/_app/cierres'
      path: '/cierres'
      fullPath: '/cierres'
      preLoaderRoute: typeof AppCierresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bodega': {
      id: '/_app/bodega'
      path: '/bodega'
      fullPath: '/bodega'
      preLoaderRoute: typeof AppBodegaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordenes/': {
      id: '/_app/ordenes/'
      path: '/ordenes'
      fullPath: '/ordenes/'
      preLoaderRoute: typeof AppOrdenesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$clienteId': {
      id: '/_app/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBodegaRoute: typeof AppBodegaRoute
  AppCierresRoute: typeof AppCierresRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppCostosRoute: typeof AppCostosRoute
  AppCotizacionesRoute: typeof AppCotizacionesRoute
  AppGruasRoute: typeof AppGruasRoute
  AppOperadoresRoute: typeof AppOperadoresRoute
  AppOrdenesCompraRoute: typeof AppOrdenesCompraRoute
  AppVehiculosRoute: typeof AppVehiculosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppOrdenesIndexRoute: typeof AppOrdenesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBodegaRoute: AppBodegaRoute,
  AppCierresRoute: AppCierresRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppCostosRoute: AppCostosRoute,
  AppCotizacionesRoute: AppCotizacionesRoute,
  AppGruasRoute: AppGruasRoute,
  AppOperadoresRoute: AppOperadoresRoute,
  AppOrdenesCompraRoute: AppOrdenesCompraRoute,
  AppVehiculosRoute: AppVehiculosRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesClienteIdRoute: AppClientesClienteIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppOrdenesIndexRoute: AppOrdenesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
